changelog:
  categories:
    - title: ✨ Features
      labels:
        - feature
        - enhancement
    - title: 🐛 Bug Fixes
      labels:
        - bug
        - fix
    - title: 📚 Documentation
      labels:
        - documentation
        - docs
    - title: 🔧 Maintenance
      labels:
        - maintenance
        - chore
    - title: 📦 Dependencies
      labels:
        - dependencies
        - github-actions
    - title: Other Changes
      labels:
        - "*"
